import type { AnswerValue, EvaluationEffect, QuestionDefinition } from './catalog-types'

const standardEvaluation = {
  yes: { status: 'compliant', reason_code: 'answer_yes' },
  no: { status: 'non_compliant', reason_code: 'answer_no' },
  unknown: { status: 'not_evaluable', reason_code: 'answer_unknown' },
  not_applicable: { status: 'not_evaluable', reason_code: 'justified_not_applicable' },
} satisfies Record<AnswerValue, EvaluationEffect>

const validity = (essential = 365, reinforced = 180) => ({ essential, reinforced })

export const QUESTION_CATALOG = [
  {
    key: 'access.individual_accounts',
    version: 1,
    control_keys: ['A.5.15'],
    scope: 'organization',
    policies: ['essential', 'reinforced'],
    prompt: 'Does each person use their own account to access company systems?',
    help_text: 'Think about email, shared tools and the systems used during a normal workday.',
    why_it_matters:
      'Personal accounts make it possible to remove access for one person without interrupting everyone else.',
    inherits_to: ['office', 'asset'],
    validity_days: validity(),
    evaluation: standardEvaluation,
  },
  {
    key: 'access.lifecycle_process',
    version: 1,
    control_keys: ['A.5.15'],
    scope: 'organization',
    policies: ['essential', 'reinforced'],
    prompt: 'When someone changes roles or leaves, are their old permissions removed?',
    help_text: 'Consider what normally happens with their email, shared folders and business apps.',
    why_it_matters:
      'Old access can let former staff or people in a new role see information they no longer need.',
    inherits_to: ['office', 'asset'],
    validity_days: validity(),
    evaluation: standardEvaluation,
  },
  {
    key: 'access.periodic_review',
    version: 1,
    control_keys: ['A.5.15'],
    scope: 'organization',
    policies: ['reinforced'],
    prompt: 'Does the company regularly check who still needs access to its systems?',
    help_text: 'A simple recurring review of people and their access is enough.',
    why_it_matters:
      'A quick recurring check catches forgotten accounts and permissions before they become a problem.',
    inherits_to: ['office', 'asset'],
    validity_days: validity(),
    dependencies: [{ type: 'policy_includes', policies: ['reinforced'] }],
    evaluation: standardEvaluation,
  },
  {
    key: 'backup.managed_recovery',
    version: 1,
    control_keys: ['A.8.13'],
    scope: 'organization',
    policies: ['essential', 'reinforced'],
    prompt: 'Does the company have a regular way to save and recover important work files?',
    help_text: 'For example, managed backups or company cloud storage with recovery available.',
    why_it_matters:
      'A recoverable copy keeps an accident, theft or broken computer from stopping the business.',
    inherits_to: ['office', 'asset'],
    validity_days: validity(),
    evaluation: standardEvaluation,
  },
  {
    key: 'backup.restore_tested',
    version: 1,
    control_keys: ['A.8.13'],
    scope: 'organization',
    policies: ['reinforced'],
    prompt: 'Has the company successfully recovered a file during this review period?',
    help_text: 'A real recovery of a deleted or previous file version counts.',
    why_it_matters:
      'Trying a real recovery confirms that the saved copy can actually be used when it is needed.',
    inherits_to: ['office', 'asset'],
    validity_days: validity(180, 180),
    evidence_note_required_for: ['yes'],
    dependencies: [
      { type: 'policy_includes', policies: ['reinforced'] },
      {
        type: 'requires_question_answer',
        question_key: 'backup.managed_recovery',
        answers: ['yes'],
      },
    ],
    evaluation: standardEvaluation,
  },
  {
    key: 'software.approval_rule',
    version: 1,
    control_keys: ['A.8.19'],
    scope: 'organization',
    policies: ['essential', 'reinforced'],
    prompt: 'Does the company have a clear rule about which apps people may install?',
    help_text: 'Think about the everyday rule people follow, whether written down or communicated.',
    why_it_matters: 'A clear rule reduces accidental installation of unsafe or unlicensed apps.',
    inherits_to: ['office', 'asset'],
    validity_days: validity(),
    evaluation: standardEvaluation,
  },
  {
    key: 'network.guest_separation',
    version: 1,
    control_keys: ['A.8.22'],
    scope: 'office',
    policies: ['essential', 'reinforced'],
    prompt: 'Do visitors and personal devices use Wi-Fi separate from work devices?',
    help_text: 'Answer based on how people connect in this office; no network details are needed.',
    why_it_matters:
      'Keeping visitors apart prevents their phones or laptops from reaching company equipment.',
    validity_days: validity(),
    evaluation: standardEvaluation,
  },
  {
    key: 'network.zones_documented',
    version: 1,
    control_keys: ['A.8.22'],
    scope: 'office',
    policies: ['reinforced'],
    prompt: 'Is there an up-to-date record of which network each kind of device should use?',
    help_text:
      'For example, a simple record separating work devices, visitors and office equipment.',
    why_it_matters:
      'A simple, current record helps people connect each device in the right place and spot mistakes.',
    validity_days: validity(),
    dependencies: [{ type: 'policy_includes', policies: ['reinforced'] }],
    evaluation: standardEvaluation,
  },
  {
    key: 'endpoint.authorized_users',
    version: 1,
    control_keys: ['A.8.1'],
    scope: 'asset',
    policies: ['essential', 'reinforced'],
    prompt: 'Is this computer used only by people authorized by the company?',
    help_text: 'Think about who normally signs in or uses it during the workday.',
    why_it_matters:
      'Limiting use protects the company information stored on or reachable from this computer.',
    applies_to_asset_types: ['workstation'],
    validity_days: validity(),
    evaluation: standardEvaluation,
  },
  {
    key: 'endpoint.unlock_authentication',
    version: 1,
    control_keys: ['A.8.5'],
    scope: 'asset',
    policies: ['essential', 'reinforced'],
    prompt: 'Does this computer ask for a password, PIN or fingerprint when it is unlocked?',
    help_text: 'Answer based on what the person using it sees day to day.',
    why_it_matters:
      'A password, PIN or fingerprint prevents someone nearby from opening an unattended computer.',
    applies_to_asset_types: ['workstation'],
    validity_days: validity(),
    evaluation: standardEvaluation,
  },
  {
    key: 'endpoint.automatic_lock',
    version: 1,
    control_keys: ['A.8.5'],
    scope: 'asset',
    policies: ['essential', 'reinforced'],
    prompt: 'Does this computer lock itself after nobody uses it for a while?',
    help_text: 'It should require the person to sign in again before continuing.',
    why_it_matters:
      'Automatic locking protects the computer when someone steps away and forgets to lock it.',
    applies_to_asset_types: ['workstation'],
    validity_days: validity(),
    evaluation: standardEvaluation,
  },
  {
    key: 'malware.protection_active',
    version: 1,
    control_keys: ['A.8.7'],
    scope: 'asset',
    policies: ['essential', 'reinforced'],
    prompt: 'Is protection against viruses and harmful apps turned on for this computer?',
    help_text: 'Use what the computer or the person responsible for it normally reports.',
    why_it_matters:
      'Active protection can stop common malicious files before they damage work or steal information.',
    applies_to_asset_types: ['workstation'],
    validity_days: validity(),
    evaluation: standardEvaluation,
  },
  {
    key: 'malware.protection_current',
    version: 1,
    control_keys: ['A.8.7'],
    scope: 'asset',
    policies: ['essential', 'reinforced'],
    prompt: 'Is that protection up to date and free of unresolved warnings?',
    help_text: 'Choose “I don’t know” if its current status cannot be checked easily.',
    why_it_matters:
      'Outdated protection may miss newer threats, and unresolved warnings can mean the device is exposed.',
    applies_to_asset_types: ['workstation'],
    validity_days: validity(),
    evaluation: standardEvaluation,
  },
  {
    key: 'backup.endpoint_covered',
    version: 1,
    control_keys: ['A.8.13'],
    scope: 'asset',
    policies: ['essential', 'reinforced'],
    prompt: 'Are important work files from this computer included in the company recovery method?',
    help_text: 'This can include managed backup or approved company cloud storage.',
    why_it_matters:
      'Including this computer means its important work can be recovered if it is lost or damaged.',
    applies_to_asset_types: ['workstation'],
    validity_days: validity(),
    evaluation: standardEvaluation,
  },
  {
    key: 'software.install_restricted',
    version: 1,
    control_keys: ['A.8.19'],
    scope: 'asset',
    policies: ['essential', 'reinforced'],
    prompt: 'Does installing an app require approval or an administrator password?',
    help_text:
      'This checks the device itself, separately from the company rule. Answer based on what happens when someone tries to install software on this computer.',
    why_it_matters: 'Approval reduces the chance of unsafe software being installed by mistake.',
    applies_to_asset_types: ['workstation'],
    validity_days: validity(),
    evaluation: standardEvaluation,
  },
] as const satisfies readonly QuestionDefinition[]
