'use client'

import { useState } from 'react'
import { Button, Divider, Group, Modal, SegmentedControl, Stack, Text } from '@mantine/core'
import { Download, ShieldAlert, ShieldCheck } from 'lucide-react'
import type { Office } from '@/app/types/payload-types'
import type { AgentPlatform } from '@/domain/agents/buildAgentPackage'
import { useProvisionAgent } from '../hooks/use-offices'
import { useRevokeAgent } from '../hooks/use-offices'
import type { AgentQuotaSummary, OfficeAgentSummary } from '@/endpoints/officeAgentSummary'
import { AgentConnectivityBadge } from './AgentConnectivityBadge'

const PLATFORM_OPTIONS = [
  { label: 'Linux / macOS', value: 'posix' },
  { label: 'Windows', value: 'windows' },
]

// El paquete trae solo el launcher del SO elegido (domain/agents/buildAgentPackage.ts), así que
// el texto nombra el archivo que el usuario va a encontrar adentro y no uno genérico.
const PLATFORM_HINT: Record<AgentPlatform, string> = {
  posix:
    'The package contains Python source, requirements, the start-agent.sh launcher and an autogenerated configuration file.',
  windows:
    'The package contains Python source, requirements, the start-agent.cmd and start-agent.ps1 launchers and an autogenerated configuration file.',
}

function downloadBlob(blob: Blob, officeName: string, platform: AgentPlatform) {
  const url = URL.createObjectURL(blob)
  const anchor = document.createElement('a')
  anchor.href = url
  anchor.download = `siam-agent-${officeName.toLowerCase().replace(/[^a-z0-9]+/g, '-')}-${platform}.zip`
  anchor.click()
  URL.revokeObjectURL(url)
}

export function AgentProvisionModal({
  office,
  opened,
  onClose,
  summary,
  quota,
}: {
  office: Office | null
  opened: boolean
  onClose: () => void
  summary?: OfficeAgentSummary
  quota: AgentQuotaSummary | null
}) {
  const provision = useProvisionAgent()
  const revoke = useRevokeAgent()
  const [platform, setPlatform] = useState<AgentPlatform>('posix')
  const [agentToDeactivate, setAgentToDeactivate] = useState<string | null>(null)
  // quota.available ya viene resuelto server-side como min(cupo de organización, cupo de esta
  // oficina) — ver domain/subscriptions/agent-quota.ts::getAgentQuota. Recalcular acá solo la
  // mitad "por oficina" podía habilitar el botón con el cupo de organización ya agotado.
  const officeSlotsAvailable = quota?.available

  function handleClose() {
    setPlatform('posix')
    setAgentToDeactivate(null)
    onClose()
  }

  function handleProvision() {
    if (!office) return
    provision.mutate(
      { officeId: String(office.id), platform },
      {
        onSuccess: blob => {
          downloadBlob(blob, office.name, platform)
          handleClose()
        },
      }
    )
  }

  function confirmDeactivation() {
    if (!agentToDeactivate) return
    revoke.mutate(agentToDeactivate, {
      onSuccess: () => setAgentToDeactivate(null),
    })
  }

  const hasAgents = (summary?.total ?? 0) > 0

  return (
    <>
      <Modal
        opened={opened}
        onClose={handleClose}
        title={hasAgents ? 'Manage scanners' : 'Install scanner'}
        centered
        size="md"
      >
        <Stack gap="md">
          <Group gap="sm" align="flex-start" wrap="nowrap">
            <ShieldCheck size={22} strokeWidth={1.5} />
            <Stack gap={4} style={{ minWidth: 0 }}>
              <Text fw={600}>{office?.name}</Text>
              <Text size="sm" c="dimmed">
                A new agent credential and a ready-to-run source package will be downloaded for this
                office.
              </Text>
            </Stack>
          </Group>
          {hasAgents && (
            <Stack gap="xs">
              <Text size="sm" fw={600}>
                Existing scanners
              </Text>
              {summary?.agents.map(agent => (
                <Group key={agent.id} justify="space-between" gap="sm">
                  <Stack gap={2} style={{ minWidth: 0 }}>
                    <Text size="sm" truncate>
                      {agent.id}
                    </Text>
                    <AgentConnectivityBadge
                      connectivity={agent.connectivity}
                      revocationReason={agent.revocation_reason}
                    />
                  </Stack>
                  {agent.lifecycle_status !== 'revoked' && (
                    <Button
                      size="xs"
                      color="red"
                      variant="light"
                      loading={revoke.isPending}
                      onClick={() => setAgentToDeactivate(agent.id)}
                    >
                      Deactivate
                    </Button>
                  )}
                </Group>
              ))}
            </Stack>
          )}
          {hasAgents && <Divider label="Add another scanner" labelPosition="left" />}
          <Stack gap={6}>
            <Text size="sm" fw={500}>
              Operating system
            </Text>
            <SegmentedControl
              fullWidth
              data={PLATFORM_OPTIONS}
              value={platform}
              onChange={value => setPlatform(value as AgentPlatform)}
              disabled={provision.isPending}
            />
          </Stack>
          <Text size="sm" c="dimmed">
            {PLATFORM_HINT[platform]}
          </Text>
          {quota && (
            <Stack gap={2}>
              <Text size="sm" fw={500}>
                Scanner slots: {quota.used} of {quota.limit} in use
              </Text>
              {quota.per_office !== null && (
                <Text size="xs" c="dimmed">
                  This office: {summary?.active ?? 0} of {quota.per_office} in use
                </Text>
              )}
            </Stack>
          )}
          <Group justify="flex-end" wrap="wrap">
            <Button variant="default" onClick={handleClose} disabled={provision.isPending}>
              Cancel
            </Button>
            <Button
              leftSection={<Download size={16} strokeWidth={1.5} />}
              loading={provision.isPending}
              disabled={officeSlotsAvailable === 0}
              onClick={handleProvision}
            >
              Generate and download
            </Button>
          </Group>
        </Stack>
      </Modal>
      <Modal
        opened={agentToDeactivate !== null}
        onClose={() => !revoke.isPending && setAgentToDeactivate(null)}
        title="Deactivate scanner"
        centered
        size="sm"
        closeOnClickOutside={!revoke.isPending}
        closeOnEscape={!revoke.isPending}
        withCloseButton={!revoke.isPending}
      >
        <Stack gap="lg">
          <Group align="flex-start" wrap="nowrap">
            <ShieldAlert size={24} color="var(--mantine-color-red-6)" strokeWidth={1.5} />
            <Stack gap={4}>
              <Text fw={600}>This action is permanent</Text>
              <Text size="sm" c="dimmed">
                The scanner credential will stop working immediately. To reconnect this office, you
                will need to install a new scanner.
              </Text>
              <Text size="xs" c="dimmed">
                Scanner: {agentToDeactivate}
              </Text>
            </Stack>
          </Group>
          <Group justify="flex-end">
            <Button
              variant="default"
              disabled={revoke.isPending}
              onClick={() => setAgentToDeactivate(null)}
            >
              Cancel
            </Button>
            <Button color="red" loading={revoke.isPending} onClick={confirmDeactivation}>
              Deactivate scanner
            </Button>
          </Group>
        </Stack>
      </Modal>
    </>
  )
}
