'use client'

import { useState } from 'react'
import { Button, Group, Modal, SegmentedControl, Stack, Text } from '@mantine/core'
import { Download, ShieldCheck } from 'lucide-react'
import type { Office } from '@/app/types/payload-types'
import type { AgentPlatform } from '@/domain/agents/buildAgentPackage'
import { useProvisionAgent } from '../hooks/use-offices'

const PLATFORM_OPTIONS = [
  { label: 'Linux / macOS', value: 'posix' },
  { label: 'Windows', value: 'windows' },
]

// El paquete trae solo el launcher del SO elegido (domain/agents/buildAgentPackage.ts), así que
// el texto nombra el archivo que el usuario va a encontrar adentro y no uno genérico.
const PLATFORM_HINT: Record<AgentPlatform, string> = {
  posix: 'The package contains Python source, requirements, the start-agent.sh launcher and an autogenerated configuration file.',
  windows:
    'The package contains Python source, requirements, the start-agent.cmd and start-agent.ps1 launchers and an autogenerated configuration file.',
}

function downloadBlob(blob: Blob, officeName: string, platform: AgentPlatform) {
  const url = URL.createObjectURL(blob)
  const anchor = document.createElement('a')
  anchor.href = url
  anchor.download = `siam-agent-${officeName.toLowerCase().replace(/[^a-z0-9]+/g, '-')}-${platform}.zip`
  anchor.click()
  URL.revokeObjectURL(url)
}

export function AgentProvisionModal({
  office,
  opened,
  onClose,
}: {
  office: Office | null
  opened: boolean
  onClose: () => void
}) {
  const provision = useProvisionAgent()
  const [platform, setPlatform] = useState<AgentPlatform>('posix')

  function handleClose() {
    setPlatform('posix')
    onClose()
  }

  function handleProvision() {
    if (!office) return
    provision.mutate(
      { officeId: String(office.id), platform },
      {
        onSuccess: blob => {
          downloadBlob(blob, office.name, platform)
          handleClose()
        },
      }
    )
  }

  return (
    <Modal opened={opened} onClose={handleClose} title="Install scanner" centered size="md">
      <Stack gap="md">
        <Group gap="sm" align="flex-start" wrap="nowrap">
          <ShieldCheck size={22} strokeWidth={1.5} />
          <Stack gap={4} style={{ minWidth: 0 }}>
            <Text fw={600}>{office?.name}</Text>
            <Text size="sm" c="dimmed">
              A new agent credential and a ready-to-run source package will be downloaded for this
              office.
            </Text>
          </Stack>
        </Group>
        <Stack gap={6}>
          <Text size="sm" fw={500}>
            Operating system
          </Text>
          <SegmentedControl
            fullWidth
            data={PLATFORM_OPTIONS}
            value={platform}
            onChange={value => setPlatform(value as AgentPlatform)}
            disabled={provision.isPending}
          />
        </Stack>
        <Text size="sm" c="dimmed">
          {PLATFORM_HINT[platform]}
        </Text>
        <Group justify="flex-end" wrap="wrap">
          <Button variant="default" onClick={handleClose} disabled={provision.isPending}>
            Cancel
          </Button>
          <Button
            leftSection={<Download size={16} strokeWidth={1.5} />}
            loading={provision.isPending}
            onClick={handleProvision}
          >
            Generate and download
          </Button>
        </Group>
      </Stack>
    </Modal>
  )
}
