'use client'

import { Button, Group, Modal, Stack, Text } from '@mantine/core'
import { Download, ShieldCheck } from 'lucide-react'
import type { Office } from '@/app/types/payload-types'
import { useProvisionAgent } from '../hooks/use-offices'

function downloadBlob(blob: Blob, officeName: string) {
  const url = URL.createObjectURL(blob)
  const anchor = document.createElement('a')
  anchor.href = url
  anchor.download = `siam-agent-${officeName.toLowerCase().replace(/[^a-z0-9]+/g, '-')}.zip`
  anchor.click()
  URL.revokeObjectURL(url)
}

export function AgentProvisionModal({
  office,
  opened,
  onClose,
}: {
  office: Office | null
  opened: boolean
  onClose: () => void
}) {
  const provision = useProvisionAgent()

  function handleProvision() {
    if (!office) return
    provision.mutate(String(office.id), {
      onSuccess: blob => {
        downloadBlob(blob, office.name)
        onClose()
      },
    })
  }

  return (
    <Modal opened={opened} onClose={onClose} title="Install scanner" centered size="md">
      <Stack gap="md">
        <Group gap="sm" align="flex-start" wrap="nowrap">
          <ShieldCheck size={22} strokeWidth={1.5} />
          <Stack gap={4} style={{ minWidth: 0 }}>
            <Text fw={600}>{office?.name}</Text>
            <Text size="sm" c="dimmed">
              A new agent credential and a ready-to-run source package will be downloaded for this
              office.
            </Text>
          </Stack>
        </Group>
        <Text size="sm" c="dimmed">
          The package contains Python source, requirements, a launcher script and an autogenerated
          configuration file.
        </Text>
        <Group justify="flex-end" wrap="wrap">
          <Button variant="default" onClick={onClose} disabled={provision.isPending}>
            Cancel
          </Button>
          <Button
            leftSection={<Download size={16} strokeWidth={1.5} />}
            loading={provision.isPending}
            onClick={handleProvision}
          >
            Generate and download
          </Button>
        </Group>
      </Stack>
    </Modal>
  )
}
