import fs from 'node:fs/promises'
import path from 'node:path'
import JSZip from 'jszip'

export interface AgentPackageConfig {
  agentId: string
  platformToken: string
  platformUrl: string
  heartbeatUrl: string
}

const scannerRoot = () =>
  process.env.SCANNER_SOURCE_ROOT || path.resolve(process.cwd(), '../scanner-prototype')

async function addDirectory(zip: JSZip, sourceDirectory: string, archiveDirectory: string) {
  const entries = await fs.readdir(sourceDirectory, { withFileTypes: true })
  for (const entry of entries) {
    if (entry.name === '__pycache__' || entry.name.endsWith('.pyc')) continue
    const sourcePath = path.join(sourceDirectory, entry.name)
    const archivePath = `${archiveDirectory}/${entry.name}`
    if (entry.isSymbolicLink()) throw new Error(`Symlink no permitido en el paquete: ${sourcePath}`)
    if (entry.isDirectory()) {
      await addDirectory(zip, sourcePath, archivePath)
    } else if (entry.isFile()) {
      zip.file(archivePath, await fs.readFile(sourcePath))
    }
  }
}

function generatedEnv(config: AgentPackageConfig) {
  return [
    `AGENT_ID=${config.agentId}`,
    `PLATFORM_TOKEN=${config.platformToken}`,
    `PLATFORM_URL=${config.platformUrl}`,
    `HEARTBEAT_URL=${config.heartbeatUrl}`,
    '',
  ].join('\n')
}

function generatedReadme() {
  return `# SIAM Agent

This package is preconfigured for one SIAM office. Do not edit .env: it contains the
agent identity and credential generated by the platform.

## Linux and macOS

Requirements: Python 3.10+, python3-venv, and nmap.

On Ubuntu/Debian:

  sudo apt install python3 python3-venv nmap

On macOS with Homebrew:

  brew install python nmap

Run one scan:

  chmod +x start-agent.sh
  ./start-agent.sh --once

Run continuously:

  ./start-agent.sh

To scan a specific network:

  ./start-agent.sh --once --network 192.168.1.0/24

The first run creates a local virtual environment and installs requirements.txt.
The launcher is a source script; this package does not contain native binaries.

## Permissions

Without elevated permissions the agent falls back to an unprivileged TCP-connect
scan. Run with sudo only when raw-socket scans or OS detection are required:

  sudo ./start-agent.sh --once

## Troubleshooting

- A 401 response means the agent credential is invalid or revoked. Download a new
  package from Administration > Offices.
- If the platform is unreachable, verify PLATFORM_URL in .env and network access.
- The scanner must be installed on the network represented by this office.
`
}

export async function buildAgentPackage(config: AgentPackageConfig): Promise<Uint8Array> {
  const root = scannerRoot()
  const zip = new JSZip()

  await addDirectory(zip, path.join(root, 'src', 'siam_agent'), 'src/siam_agent')
  zip.file('requirements.txt', await fs.readFile(path.join(root, 'requirements.txt')))

  zip.file(
    'start-agent.sh',
    [
      '#!/usr/bin/env bash',
      'set -a',
      'source "$(dirname "${BASH_SOURCE[0]}")/.env"',
      'set +a',
      '',
      'SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"',
      'PYTHON_BIN="${PYTHON_BIN:-python3}"',
      'VENV_DIR="$SCRIPT_DIR/.siam-agent-venv"',
      'if [ ! -x "$VENV_DIR/bin/python" ]; then',
      '  "$PYTHON_BIN" -m venv "$VENV_DIR"',
      '  "$VENV_DIR/bin/python" -m pip install -r "$SCRIPT_DIR/requirements.txt"',
      'fi',
      'PYTHONPATH="$SCRIPT_DIR/src" exec "$VENV_DIR/bin/python" -m siam_agent.agent "$@"',
    ].join('\n'),
    { unixPermissions: '755' }
  )
  zip.file('.env', generatedEnv(config), { unixPermissions: '600' })
  zip.file('README.md', generatedReadme())

  return zip.generateAsync({ type: 'uint8array', compression: 'DEFLATE' })
}
