/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    admins: AdminAuthOperations;
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    organizations: Organization;
    offices: Office;
    agents: Agent;
    assets: Asset;
    'non-network-assets': NonNetworkAsset;
    'scan-reports': ScanReport;
    roles: Role;
    'organization-settings': OrganizationSetting;
    subscriptions: Subscription;
    admins: Admin;
    users: User;
    'organization-memberships': OrganizationMembership;
    'job-runs': JobRun;
    'inventory-snapshots': InventorySnapshot;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    organizations: OrganizationsSelect<false> | OrganizationsSelect<true>;
    offices: OfficesSelect<false> | OfficesSelect<true>;
    agents: AgentsSelect<false> | AgentsSelect<true>;
    assets: AssetsSelect<false> | AssetsSelect<true>;
    'non-network-assets': NonNetworkAssetsSelect<false> | NonNetworkAssetsSelect<true>;
    'scan-reports': ScanReportsSelect<false> | ScanReportsSelect<true>;
    roles: RolesSelect<false> | RolesSelect<true>;
    'organization-settings': OrganizationSettingsSelect<false> | OrganizationSettingsSelect<true>;
    subscriptions: SubscriptionsSelect<false> | SubscriptionsSelect<true>;
    admins: AdminsSelect<false> | AdminsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'organization-memberships': OrganizationMembershipsSelect<false> | OrganizationMembershipsSelect<true>;
    'job-runs': JobRunsSelect<false> | JobRunsSelect<true>;
    'inventory-snapshots': InventorySnapshotsSelect<false> | InventorySnapshotsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: Admin | User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface AdminAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organizations".
 */
export interface Organization {
  id: string;
  name: string;
  is_active?: boolean | null;
  settings?: (string | null) | OrganizationSetting;
  subscription?: (string | null) | Subscription;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organization-settings".
 */
export interface OrganizationSetting {
  id: string;
  organization: string | Organization;
  industry: string;
  risk_score_policy?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  offline_after_hours?: number | null;
  snapshot_before_each_scan?: boolean | null;
  snapshot_interval_days?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscriptions".
 */
export interface Subscription {
  id: string;
  organization: string | Organization;
  level: 'basic' | 'premium' | 'custom';
  max_users?: number | null;
  max_offices?: number | null;
  /**
   * Mapa plano feature_key -> boolean, ver domain/subscriptions/features.ts
   */
  features?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offices".
 */
export interface Office {
  id: string;
  organization: string | Organization;
  name: string;
  county_fips?: string | null;
  is_active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agents".
 */
export interface Agent {
  /**
   * agent_id tal cual lo manda el escáner (ej. agent-001)
   */
  id: string;
  office: string | Office;
  organization?: (string | null) | Organization;
  last_heartbeat_at?: string | null;
  status?: ('online' | 'offline') | null;
  /**
   * false = token revocado, rechazar toda ingesta de este agente
   */
  is_active?: boolean | null;
  failedAttempts?: number | null;
  apiKeyPrefix?: string | null;
  apiKeyHash?: string | null;
  /**
   * Solo visible una vez, en la respuesta de creación.
   */
  apiKey?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assets".
 */
export interface Asset {
  id: string;
  asset_id: string;
  agent: string | Agent;
  office?: (string | null) | Office;
  organization?: (string | null) | Organization;
  ip?: string | null;
  last_seen?: string | null;
  gateway_ip?: string | null;
  gateway_mac?: string | null;
  mac?: string | null;
  vendor?: string | null;
  hostname?: string | null;
  os?: {
    name?: string | null;
    accuracy?: number | null;
    cpe?: string[] | null;
  };
  services?:
    | {
        port?: number | null;
        protocol?: string | null;
        state?: string | null;
        name?: string | null;
        product?: string | null;
        version?: string | null;
        extra_info?: string | null;
        cpe?: string | null;
        id?: string | null;
      }[]
    | null;
  identified?: boolean | null;
  alias?: string | null;
  criticality?: ('low' | 'medium' | 'high' | 'critical') | null;
  owner?: (string | null) | User;
  location?: string | null;
  status?: ('active' | 'retired' | 'offline') | null;
  first_viewed_at?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name: string;
  status?: ('active' | 'inactive') | null;
  organization_membership?: (string | null) | OrganizationMembership;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organization-memberships".
 */
export interface OrganizationMembership {
  id: string;
  user: string | User;
  organization: string | Organization;
  offices?: (string | Office)[] | null;
  role: string | Role;
  status?: ('onboarding' | 'active') | null;
  is_active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roles".
 */
export interface Role {
  id: string;
  slug: string;
  name: string;
  /**
   * 1 = máxima autoridad
   */
  rank: number;
  scope: 'platform' | 'organization' | 'organization_office' | 'office_user';
  is_platform_role?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "non-network-assets".
 */
export interface NonNetworkAsset {
  id: string;
  alias: string;
  asset_category: 'antivirus_edr' | 'software_license' | 'cloud_asset' | 'backup' | 'other';
  criticality: 'low' | 'medium' | 'high' | 'critical';
  owner: string | User;
  location?: string | null;
  status?: ('active' | 'retired') | null;
  review_interval: 'never' | '1d' | '3d' | '1w' | '1m' | '6m' | '1y';
  next_review_at?: string | null;
  last_reviewed_at?: string | null;
  review_status?: string | null;
  can_review?: boolean | null;
  related_assets?: (string | Asset)[] | null;
  office: string | Office;
  organization: string | Organization;
  last_updated_at?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scan-reports".
 */
export interface ScanReport {
  /**
   * report_id tal cual lo manda el escáner
   */
  id: string;
  agent: string | Agent;
  office?: (string | null) | Office;
  network?: string | null;
  scan_start?: string | null;
  scan_end?: string | null;
  hosts_up?: number | null;
  gateway_ip?: string | null;
  gateway_mac?: string | null;
  raw_payload?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  status?: ('received' | 'processed' | 'failed') | null;
  processed_at?: string | null;
  error?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins".
 */
export interface Admin {
  id: string;
  role: string | Role;
  status?: ('active' | 'inactive') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'admins';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-runs".
 */
export interface JobRun {
  id: string;
  job_type: 'aging_sweep';
  started_at: string;
  finished_at?: string | null;
  status: 'running' | 'success' | 'failed';
  summary?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  error?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inventory-snapshots".
 */
export interface InventorySnapshot {
  id: string;
  organization: string | Organization;
  office: string | Office;
  taken_at: string;
  generated_by: 'manual' | 'scheduled' | 'pre_audit';
  triggered_by_user?: (string | null) | User;
  risk_score: {
    global: number;
    policy_snapshot?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  assets_dump:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'organizations';
        value: string | Organization;
      } | null)
    | ({
        relationTo: 'offices';
        value: string | Office;
      } | null)
    | ({
        relationTo: 'agents';
        value: string | Agent;
      } | null)
    | ({
        relationTo: 'assets';
        value: string | Asset;
      } | null)
    | ({
        relationTo: 'non-network-assets';
        value: string | NonNetworkAsset;
      } | null)
    | ({
        relationTo: 'scan-reports';
        value: string | ScanReport;
      } | null)
    | ({
        relationTo: 'roles';
        value: string | Role;
      } | null)
    | ({
        relationTo: 'organization-settings';
        value: string | OrganizationSetting;
      } | null)
    | ({
        relationTo: 'subscriptions';
        value: string | Subscription;
      } | null)
    | ({
        relationTo: 'admins';
        value: string | Admin;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'organization-memberships';
        value: string | OrganizationMembership;
      } | null)
    | ({
        relationTo: 'job-runs';
        value: string | JobRun;
      } | null)
    | ({
        relationTo: 'inventory-snapshots';
        value: string | InventorySnapshot;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'admins';
        value: string | Admin;
      }
    | {
        relationTo: 'users';
        value: string | User;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user:
    | {
        relationTo: 'admins';
        value: string | Admin;
      }
    | {
        relationTo: 'users';
        value: string | User;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organizations_select".
 */
export interface OrganizationsSelect<T extends boolean = true> {
  name?: T;
  is_active?: T;
  settings?: T;
  subscription?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offices_select".
 */
export interface OfficesSelect<T extends boolean = true> {
  organization?: T;
  name?: T;
  county_fips?: T;
  is_active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agents_select".
 */
export interface AgentsSelect<T extends boolean = true> {
  id?: T;
  office?: T;
  organization?: T;
  last_heartbeat_at?: T;
  status?: T;
  is_active?: T;
  failedAttempts?: T;
  apiKeyPrefix?: T;
  apiKeyHash?: T;
  apiKey?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assets_select".
 */
export interface AssetsSelect<T extends boolean = true> {
  asset_id?: T;
  agent?: T;
  office?: T;
  organization?: T;
  ip?: T;
  last_seen?: T;
  gateway_ip?: T;
  gateway_mac?: T;
  mac?: T;
  vendor?: T;
  hostname?: T;
  os?:
    | T
    | {
        name?: T;
        accuracy?: T;
        cpe?: T;
      };
  services?:
    | T
    | {
        port?: T;
        protocol?: T;
        state?: T;
        name?: T;
        product?: T;
        version?: T;
        extra_info?: T;
        cpe?: T;
        id?: T;
      };
  identified?: T;
  alias?: T;
  criticality?: T;
  owner?: T;
  location?: T;
  status?: T;
  first_viewed_at?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "non-network-assets_select".
 */
export interface NonNetworkAssetsSelect<T extends boolean = true> {
  alias?: T;
  asset_category?: T;
  criticality?: T;
  owner?: T;
  location?: T;
  status?: T;
  review_interval?: T;
  next_review_at?: T;
  last_reviewed_at?: T;
  review_status?: T;
  can_review?: T;
  related_assets?: T;
  office?: T;
  organization?: T;
  last_updated_at?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scan-reports_select".
 */
export interface ScanReportsSelect<T extends boolean = true> {
  id?: T;
  agent?: T;
  office?: T;
  network?: T;
  scan_start?: T;
  scan_end?: T;
  hosts_up?: T;
  gateway_ip?: T;
  gateway_mac?: T;
  raw_payload?: T;
  status?: T;
  processed_at?: T;
  error?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roles_select".
 */
export interface RolesSelect<T extends boolean = true> {
  slug?: T;
  name?: T;
  rank?: T;
  scope?: T;
  is_platform_role?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organization-settings_select".
 */
export interface OrganizationSettingsSelect<T extends boolean = true> {
  organization?: T;
  industry?: T;
  risk_score_policy?: T;
  offline_after_hours?: T;
  snapshot_before_each_scan?: T;
  snapshot_interval_days?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscriptions_select".
 */
export interface SubscriptionsSelect<T extends boolean = true> {
  organization?: T;
  level?: T;
  max_users?: T;
  max_offices?: T;
  features?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins_select".
 */
export interface AdminsSelect<T extends boolean = true> {
  role?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  status?: T;
  organization_membership?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organization-memberships_select".
 */
export interface OrganizationMembershipsSelect<T extends boolean = true> {
  user?: T;
  organization?: T;
  offices?: T;
  role?: T;
  status?: T;
  is_active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-runs_select".
 */
export interface JobRunsSelect<T extends boolean = true> {
  job_type?: T;
  started_at?: T;
  finished_at?: T;
  status?: T;
  summary?: T;
  error?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inventory-snapshots_select".
 */
export interface InventorySnapshotsSelect<T extends boolean = true> {
  organization?: T;
  office?: T;
  taken_at?: T;
  generated_by?: T;
  triggered_by_user?: T;
  risk_score?:
    | T
    | {
        global?: T;
        policy_snapshot?: T;
      };
  assets_dump?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}